### ISSUE TITLE
Bug: SAM Template for Typescript doesn't work

### ISSUE THREAD

**Issue by aletheia** [aws/aws-sam-cli-app-templates#352]
### Description:
Typescript project generation using SAM template procudes a project which is not usable due to a runtime error.
The function consistently fails due to an error looking for ".mjs" module.

### Steps to reproduce:
1. Run sam init
2. Select Hello World template and any of the supported NodeJS runtime
3. Select NodeJS with Typescript template
4. Run sam deploy

### Observed result:
The deployment succedes, but the endpoint returns an Internal server error. Deep diving into Lambda console to run a test event, the output is the following error
```json
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'app'",
    "Require stack:",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:996:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:21)",
    "    at async start (file:///var/runtime/index.mjs:1194:23)",
    "    at async file:///var/runtime/index.mjs:1200:1"
  ]
}
```

### Expected result:
A working hello world endpoint.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: any
2. If using SAM CLI, `sam --version`: 1.74.0
3. AWS region: any

**Comment by hnnasit** [comment]
Hi @aletheia, did you run `sam build` command before running `sam deploy`? `sam build` command transpiles the code from TypeScript to JavaScript using esbuild bundler. The endpoint should work once the project is built and deployed.

**Comment by aletheia** [comment]
🤦 I forgot to run ```sam build``` because I am accustomed to CDK where it is invoked by the framework.
It worked now.
