### ISSUE TITLE
[TypeScript template] `sam local invoke` command shows the error: Cannot find module 'app'

### ISSUE THREAD

**Issue by sultanimbayev** [aws/aws-sam-cli-app-templates#448]
There is a closed item #351. But I don't see any solution.

### Description:

The same issue [on Stackoverflow](https://stackoverflow.com/questions/73595442/aws-sam-nodejs-runtime-with-typescript-template-error). 

### Steps to reproduce:

1. run `sam init` 
3. choose the HelloWorld template for TypeScript
4. change directory to the app `cd sam-app`
5. run `sam build`
6. run `sam local invoke HelloWorldFunction --event events/event.json`

### Observed result:

```
START RequestId: becf4508-21f7-4b85-b134-4d62e0cf0309 Version: $LATEST
2023-08-30T04:01:25.596Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)","    at async start (file:///var/runtime/index.mjs:1256:23)","    at async file:///var/runtime/index.mjs:1262:1"]} 
30 Aug 2023 04:01:25,608 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
2023-08-30T04:01:25.724Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)","    at async start (file:///var/runtime/index.mjs:1256:23)","    at async file:///var/runtime/index.mjs:1262:1"]} 
END RequestId: 8e94412c-d8cf-4628-baa5-e777603f3e32
REPORT RequestId: 8e94412c-d8cf-4628-baa5-e777603f3e32  Init Duration: 0.66 ms  Duration: 287.99 mBilled Duration: 288 ms  Memory Size: 128 MB     Max Memory Used: 128 MB
{"errorType": "Runtime.ImportModuleError", "errorMessage": "Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs", "trace": ["Runtime.ImportModuleError: Error: Cannot find module 'app'", "Require stack:", "- /var/runtime/index.mjs", "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)", "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)", "    at async start (file:///var/runtime/index.mjs:1256:23)", "    at async file:///var/runtime/index.mjs:1262:1"]}
```

### Expected result:

```
START RequestId: 64bf7e54-5509-4762-a97c-3d740498d3df Version: $LATEST
END RequestId: 64bf7e54-5509-4762-a97c-3d740498d3df
REPORT RequestId: 64bf7e54-5509-4762-a97c-3d740498d3df  Init Duration: 1.09 ms  Duration: 608.42 ms       Billed Duration: 609 ms Memory Size: 128 MB     Max Memory Used: 128 MB
{"statusCode": 200, "body": "{\"message\": \"hello world\"}"}
```

### Additional environment details

1. OS: _Windows 11 Pro 22621.2134_
7. If using SAM CLI, `sam --version`: _SAM CLI, version 1.96.0_
8. AWS region: _eu-north-1 (Stockholm)_

<details>

<summary>
When running `sam local invoke HelloWorldFunction --event events/event.json --debug`
</summary>

```
2023-08-30 10:20:12,724 | Config file location:
C:\Users\Sultan_Imbayev\source\repos\allcity\samconfig.toml
2023-08-30 10:20:12,728 | Loading configuration values from [default.['local',
'invoke'].parameters] (env.command_name.section) in config file at
'C:\Users\Sultan_Imbayev\source\repos\allcity\samconfig.toml'...
2023-08-30 10:20:12,729 | Configuration values successfully loaded.
2023-08-30 10:20:12,730 | Configuration values are: {'stack_name': 'allcity'}
2023-08-30 10:20:12,737 | Using SAM Template at
C:\Users\Sultan_Imbayev\source\repos\allcity\.aws-sam\build\template.yaml
2023-08-30 10:20:12,770 | Using config file: samconfig.toml, config environment: default
2023-08-30 10:20:12,771 | Expand command line arguments to:
2023-08-30 10:20:12,772 |
--template_file=C:\Users\Sultan_Imbayev\source\repos\allcity\.aws-sam\build\template.yaml
--event=events/event.json --function_logical_id=HelloWorldFunction --no_event
--layer_cache_basedir=C:\Users\Sultan_Imbayev\AppData\Roaming\AWS SAM\layers-pkg
--container_host=localhost --container_host_interface=127.0.0.1
2023-08-30 10:20:12,774 | local invoke command is called
2023-08-30 10:20:12,783 | No Parameters detected in the template
2023-08-30 10:20:12,817 | Sam customer defined id is more priority than other IDs. Customer defined
id for resource HelloWorldFunction is HelloWorldFunction
2023-08-30 10:20:12,819 | There is no customer defined id or cdk path defined for resource
ApplicationResourceGroup, so we will use the resource logical id as the resource id
2023-08-30 10:20:12,822 | There is no customer defined id or cdk path defined for resource
ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2023-08-30 10:20:12,825 | There is no customer defined id or cdk path defined for resource
ServerlessRestApi, so we will use the resource logical id as the resource id
2023-08-30 10:20:12,827 | 0 stacks found in the template
2023-08-30 10:20:12,829 | No Parameters detected in the template
2023-08-30 10:20:12,848 | Sam customer defined id is more priority than other IDs. Customer defined
id for resource HelloWorldFunction is HelloWorldFunction
2023-08-30 10:20:12,849 | There is no customer defined id or cdk path defined for resource
ApplicationResourceGroup, so we will use the resource logical id as the resource id
2023-08-30 10:20:12,851 | There is no customer defined id or cdk path defined for resource
ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2023-08-30 10:20:12,853 | There is no customer defined id or cdk path defined for resource
ServerlessRestApi, so we will use the resource logical id as the resource id
2023-08-30 10:20:12,855 | 4 resources found in the stack
2023-08-30 10:20:12,857 | Found Serverless function with name='HelloWorldFunction' and
CodeUri='HelloWorldFunction'
2023-08-30 10:20:12,858 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to
C:\Users\Sultan_Imbayev\source\repos\allcity\.aws-sam\build\template.yaml
2023-08-30 10:20:12,867 | Found one Lambda function with name 'HelloWorldFunction'
2023-08-30 10:20:12,869 | Invoking app.lambdaHandler (nodejs18.x)
2023-08-30 10:20:12,870 | Loading AWS credentials from session with profile 'None'
2023-08-30 10:20:13,810 | Resolving code path.
Cwd=C:\Users\Sultan_Imbayev\source\repos\allcity\.aws-sam\build,
CodeUri=C:\Users\Sultan_Imbayev\source\repos\allcity\.aws-sam\build\HelloWorldFunction
2023-08-30 10:20:13,812 | Resolved absolute path to code is
C:\Users\Sultan_Imbayev\source\repos\allcity\.aws-sam\build\HelloWorldFunction
2023-08-30 10:20:13,815 | Code
C:\Users\Sultan_Imbayev\source\repos\allcity\.aws-sam\build\HelloWorldFunction is not a zip/jar    
file
2023-08-30 10:20:18,078 | Local image is up-to-date
2023-08-30 10:20:18,099 | Using local image: public.ecr.aws/lambda/nodejs:18-rapid-x86_64.

2023-08-30 10:20:18,103 | Mounting
C:\Users\Sultan_Imbayev\source\repos\allcity\.aws-sam\build\HelloWorldFunction as
/var/task:ro,delegated, inside runtime container
2023-08-30 10:20:18,961 | Starting a timer for 3 seconds for function 'HelloWorldFunction'
START RequestId: bd632657-e9cc-4730-a347-9c77ab7ce567 Version: $LATEST
2023-08-30T04:20:20.143Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)","    at async start (file:///var/runtime/index.mjs:1256:23)","    at async file:///var/runtime/index.mjs:1262:1"]}
30 Aug 2023 04:20:20,154 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
2023-08-30T04:20:20.258Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)","    at async start (file:///var/runtime/index.mjs:1256:23)","    at async file:///var/runtime/index.mjs:1262:1"]} 
END RequestId: 01b3c1a4-b863-4abb-9e16-52763cdee22e
REPORT RequestId: 01b3c1a4-b863-4abb-9e16-52763cdee22e  Init Duration: 0.09 ms  Duration: 295.26 mBilled Duration: 296 ms  Memory Size: 128 MB     Max Memory Used: 128 MB
{"errorType": "Runtime.ImportModuleError", "errorMessage": "Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs", "trace": ["Runtime.ImportModuleError: Error: Cannot find module 'app'", "Require stack:", "- /var/runtime/index.mjs", "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)", "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)", "    at async start (file:///var/runtime/index.mjs:1256:23)", "    at async file:///var/runtime/index.mjs:1262:1"]}2023-08-30 10:20:21,627 | Cleaning all decompressed code dirs         

2023-08-30 10:20:21,628 | Telemetry endpoint configured to be
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-08-30 10:20:21,915 | Telemetry endpoint configured to be
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-08-30 10:20:21,917 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId':
'eb38407e-a369-42ae-8eee-4331ed83c8c7', 'installationId': '67bd8577-8793-4f4e-aede-a466558a3c18',  
'sessionId': 'a81febc8-561a-425f-8b8a-1540dd4ec8c8', 'executionEnvironment': 'CLI', 'ci': False,   
'pyversion': '3.8.8', 'samcliVersion': '1.96.0', 'awsProfileProvided': False, 'debugFlagProvided': 
True, 'region': '', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 
'CFN', 'gitOrigin': 'ee63885e6962db2a5d6af26170ec1edfc335eec4e787218fd9dfc6b3cbcd72a5',
'projectName': '5e662bccbf0227c69d4511aa1a7cc227a4d34a72cdffb1c7dc5a0d65df5706ee', 'initialCommit':
'98db6c1a798861d77c6f678da5a542d8aeb40796b52c2203f43305405a76b66b'}, 'duration': 8858,
'exitReason': 'success', 'exitCode': 0}}]}
2023-08-30 10:20:21,917 | Unable to find Click Context for getting session_id.
2023-08-30 10:20:21,926 | Sending Telemetry: {'metrics': [{'events': {'requestId':
'6f34eb47-b07a-419f-81d2-9f3dc94890ab', 'installationId': '67bd8577-8793-4f4e-aede-a466558a3c18',  
'sessionId': 'a81febc8-561a-425f-8b8a-1540dd4ec8c8', 'executionEnvironment': 'CLI', 'ci': False,   
'pyversion': '3.8.8', 'samcliVersion': '1.96.0', 'commandName': 'sam local invoke',
'metricSpecificAttributes': {'events': [{'event_name': 'SamConfigFileExtension', 'event_value':    
'.toml', 'thread_id': 'ee67df4f72a244b1b823b7fe6be43100', 'time_stamp': '2023-08-30 04:20:12.723', 
'exception_name': None}]}}}]}
2023-08-30 10:20:22,810 |
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read 
timed out. (read timeout=0.1)
2023-08-30 10:20:22,888 |
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read 
timed out. (read timeout=0.1)
2023-08-30 10:20:22,891 | Telemetry endpoint configured to be
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-08-30 10:20:22,893 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId':
'270691f5-d554-4502-8882-9cb083e166fe', 'installationId': '67bd8577-8793-4f4e-aede-a466558a3c18',  
'sessionId': 'a81febc8-561a-425f-8b8a-1540dd4ec8c8', 'executionEnvironment': 'CLI', 'ci': False,   
'pyversion': '3.8.8', 'samcliVersion': '1.96.0', 'runtimes': ['nodejs18.x']}}]}
2023-08-30 10:20:23,745 |
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read 
timed out. (read timeout=0.1)
```

</details>

**Comment by hawflau** [comment]
Hi @sultanimbayev thanks for raising the issue. I couldn't reproduce the issue by following your steps. Could you please zip your project folder and share with me for investigation?

**Comment by jfuss** [comment]
Closing given no response. If this is still an issue, please create a new issues as closed issues are not actively monitored.
