### ISSUE TITLE
Error: Lambda Runtime dotnet5.0 and dependency manager cli-package does not have an available initialization template

### ISSUE THREAD

**Issue by PraveenPeri** [aws/aws-sam-cli-app-templates#89]
"Create new SAM application" command in VS code with dotnet5.0 image keeps failing

**Repro Steps**
1. Install AWS Toolkit for VS code
2. Press F1 and run 'AWS: Create new SAM application'
3. Choose dotnet5.0 as the image and give a project name

**Expected Result**
Scaffolds a helloworld dotnet5 application

**Actual Result**
Fails with "Error: Lambda Runtime dotnet5.0 and dependency manager cli-package does not have an available initialization template"

**Environment**
Tried on both Windows 10 and an EC2 linux machine

**AWS Toolkit Logs**
2021-03-01 22:27:25 [INFO]: Running: (not started) [/usr/local/bin/sam init --name lambda-dotnet5.0 --no-interactive --dependency-manager cli-package --package-type Image --base-image amazon/dotnet5.0-base]
2021-03-01 22:27:26 [ERROR]: Unexpected exitcode (1), expecting (0)
2021-03-01 22:27:26 [ERROR]: An error occurred while creating a new SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
2021-03-01 22:27:26 [ERROR]: Error: undefined
2021-03-01 22:27:26 [ERROR]: stderr: Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates
,Error: Lambda Runtime dotnet5.0 and dependency manager cli-package does not have an available initialization template.
2021-03-01 22:27:26 [ERROR]: stdout: 
2021-03-01 22:27:26 [ERROR]: Error creating new SAM Application: [Error: Error with child process: Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates
,Error: Lambda Runtime dotnet5.0 and dependency manager cli-package does not have an available initialization template.
	at Object.t.logAndThrowIfUnexpectedExitCode (~/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:552517)
	at Object.<anonymous> (~/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:8146184)
	at Generator.next (<anonymous>)
	at o (~/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:8145359)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
2021-03-01 22:31:58 [INFO]: Successfully sent a telemetry batch of 5

**Comment by justinmk3** [comment]
What does `sam --version` report? Try upgrading `sam`

**Comment by PraveenPeri** [comment]
1.19.1

**Comment by justinmk3** [comment]
Ok, 1.19 is up-to-date. Just for reference, on my system with `sam` 1.17, the command works:

```
$ sam init --name lambda-dotnet5.0 --no-interactive --dependency-manager cli-package --package-type Image --base-image amazon/dotnet5.0-base
Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates
```

I wonder if something changed/regressed with sam 1.19 ?

**Comment by PraveenPeri** [comment]
I downgraded all the way to 1.17 and I still see the error. What other things that SAM depends on that can possibly throw this error? What does that error even mean?

**Comment by PraveenPeri** [comment]
I figured it out. It's our VPN that's causing the problems. Disconnected it and everything started working fine.
